name: Deploy Flask app to EC2

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup SSH agent
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2 server
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@13.61.183.62 'bash ~/flask-tutorial/deploy.sh'
